services:
  web:
    build: .
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
